### ISSUE TITLE
Save dialog/file picker folders open with a single click

### ISSUE THREAD

**Issue by anewuser** [plasmazilla/mozilla-kde-support#12]
My Plasma 5.7.2 system is set to select folders and files with one click and open them with two clicks:

![screenshot](https://cloud.githubusercontent.com/assets/6733770/17267438/e4fd11f8-55df-11e6-8a25-54b062f9f50b.png)

It works as expected with native KDE applications: https://a.pomf.cat/lylkmq.webm

However, the dialog windows of your Firefox build opens them with a single click: https://a.pomf.cat/ieuvxw.webm

Is there are a way to make it respect my mouse preferences?

Ubuntu 16.04/KDE Neon 5.7
Plasma 5.7.2
KDE Frameworks 5.24.0
Qt 5.7.0
Firefox 47 from your PPA

**Comment by cassiodoroVicinetti** [comment]
Firefox still uses KDE 4 settings. Open "~/.kde/share/config/kdeglobals", search for "SingleClick" and set it to "false".

**Comment by anewuser** [comment]
@cassiodoroVicinetti grazie.
