### ISSUE TITLE
Description missing

### ISSUE THREAD

**Issue by Zhigalin** [plasmazilla/mozilla-kde-support#4]
It is nice to have a list of things that are changed with your patches, not only a link to sources.
Thanks in advance.

**Comment by shadeslayer** [comment]
You can find the changelog for the KDE patches here : http://rosenauer.org/hg/mozilla/

**Comment by Zhigalin** [comment]
Not the changelog but the difference between Standard Firefox vs Plasma-flavored Firefox

**Comment by shadeslayer** [comment]
ahhh, where would you like to see those?

**Comment by cassiodoroVicinetti** [comment]
@shadeslayer You may create a README file inside this repository.

**Comment by shadeslayer** [comment]
I'll write something up here https://github.com/plasmazilla/mozilla-kde-support/blob/master/debian/README.Debian

We can't have a README in the top level of the repo since it interferes with how our CI builds the package

**Comment by Zhigalin** [comment]
> ahhh, where would you like to see those?

In the PPA description

**Comment by Zhigalin** [comment]
Like:

> Installing firefox-plasma/thunderbird-plasma you will get:
> - Native file saving/opening dialog
> - Application bindings
> - Awesomeness

**Comment by shadeslayer** [comment]
Done.
