### ISSUE TITLE
Firefox version is not up-to-date

### ISSUE THREAD

**Issue by cassiodoroVicinetti** [plasmazilla/mozilla-kde-support#5]
Currently the Firefox version in the PPA is still 41.0.2, while the last stable Firefox version is 43.0.3.

**Comment by shadeslayer** [comment]
Builds for wily dispatched [here](https://launchpad.net/~plasmazilla/+archive/ubuntu/builds). Other supported releases to follow soon.

**Comment by shadeslayer** [comment]
All updated. Please test once the builds finish and let me know so I can update the release ppa.

**Comment by star-buck** [comment]
@Rohan: thanks for updating, please test the builds at least for yourself
and leave +1 here if its good to go.

**Comment by shadeslayer** [comment]
@star-buck I intend to test them myself too :)

**Comment by cassiodoroVicinetti** [comment]
@shadeslayer I tested successfully the wily build (amd64). Thank you!
