### ISSUE TITLE
Firefox 44 is out

### ISSUE THREAD

**Issue by cassiodoroVicinetti** [plasmazilla/mozilla-kde-support#6]

**Comment by shadeslayer** [comment]
Waiting for patches to land in the right branch here http://rosenauer.org/hg/mozilla/

**Comment by cassiodoroVicinetti** [comment]
@shadeslayer  [Patches are landed](http://rosenauer.org/hg/mozilla/rev/11475705ab0f)!

**Comment by cassiodoroVicinetti** [comment]
Thank you!
